# Configuration file for Git Operations project

# Environment settings
environments:
  development:
    git_directory: "/path/to/development/repo"
    log_level: "DEBUG"
  testing:
    git_directory: "/path/to/testing/repo"
    log_level: "INFO"
  production:
    git_directory: "/path/to/production/repo"
    log_level: "ERROR"

# Common settings
common:
  timeout: 30  # Timeout for Git operations in seconds
  retry_attempts: 3  # Number of retry attempts for failed operations

# Validation settings
validation:
  enabled: true
  rules:
    - check_git_installed: true
    - check_repo_access: true