```yaml
# Configuration file for Git Operations

# General settings
settings:
  log_level: info  # Options: debug, info, warning, error
  timeout: 30      # Timeout for operations in seconds

# Environment-specific configurations
environments:
  development:
    repo_path: "./dev_repositories"
    enable_debug: true
  testing:
    repo_path: "./test_repositories"
    enable_debug: false
  production:
    repo_path: "./prod_repositories"
    enable_debug: false

# Validation settings for repository initialization
validation:
  max_repo_name_length: 255  # Maximum allowed length for repository names
  disallowed_characters: ["*", "?", "<", ">", "|"]  # Characters not allowed in repo names
```