```ini
[DEFAULT]
# Default settings for the application
log_level = INFO
max_retries = 3

[development]
# Development environment settings
debug = True
database_url = sqlite:///dev.db

[testing]
# Testing environment settings
debug = False
database_url = sqlite:///test.db

[production]
# Production environment settings
debug = False
database_url = postgresql://user:pass@localhost/prod

[validation]
# Validation settings
enabled = True
required_fields = name, description, version
```