```ini
[DEFAULT]
# Default settings for the application
log_level = INFO
max_retries = 3
timeout = 30

[development]
# Development environment settings
debug = True
database_url = sqlite:///dev.db

[testing]
# Testing environment settings
debug = True
database_url = sqlite:///test.db
log_level = DEBUG

[production]
# Production environment settings
debug = False
database_url = postgresql://user:password@localhost/prod
log_level = ERROR

[validation]
# Configuration validation settings
enable_validation = true
validation_rules = required, format
```