```ini
# Configuration file for Git Operations

[DEFAULT]
# Default repository path
repo_path = ./repos
# Default branch name
default_branch = main

[development]
# Development environment settings
repo_path = ./dev_repos
default_branch = dev

[testing]
# Testing environment settings
repo_path = ./test_repos
default_branch = test

[production]
# Production environment settings
repo_path = ./prod_repos
default_branch = main

# Validation for the repo path
[validation]
# Ensure the repo path is a valid directory
require_valid_path = True
```