```yaml
# Configuration file for Git Operations

# Define the environments for the application
environments:
  development:
    # Directory for development repositories
    repo_directory: "./dev_repos"
    # Git user settings
    git_user:
      name: "Dev User"
      email: "dev@example.com"
      
  testing:
    # Directory for testing repositories
    repo_directory: "./test_repos"
    git_user:
      name: "Test User"
      email: "test@example.com"
      
  production:
    # Directory for production repositories
    repo_directory: "./prod_repos"
    git_user:
      name: "Prod User"
      email: "prod@example.com"

# Validation settings
validation:
  enabled: true
  rules:
    - rule: "check_repo_exists"
      message: "Repository already exists."
    - rule: "check_valid_email"
      message: "Invalid email format."

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "git_operations.log"
```