```yaml
# Configuration file for Git Operations project

# General settings
general:
  app_name: "GitOperations"
  version: "1.0.0"
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Environment-specific settings
environments:
  development:
    debug: true
    git_path: "/usr/bin/git"
  testing:
    debug: false
    git_path: "/usr/bin/git"
  production:
    debug: false
    git_path: "/usr/bin/git"

# Repository settings
repository:
  default_name: "my_repo"
  max_repos: 10  # Maximum number of repositories allowed

# Validation settings
validation:
  enable: true
  rules:
    name_length: 
      min: 3
      max: 50
    allowed_characters: "^[a-zA-Z0-9_-]+$"  # Alphanumeric, underscores, and dashes
```