```yaml
# Configuration file for GitOperations project

# Default environment settings
default:
  repo_name: "default_repo"  # Default name for the Git repository
  base_dir: "/tmp/git_ops"   # Base directory for repository creation

# Development environment settings
development:
  repo_name: "dev_repo"
  base_dir: "/home/user/dev/git_ops"

# Testing environment settings
testing:
  repo_name: "test_repo"
  base_dir: "/home/user/test/git_ops"

# Production environment settings
production:
  repo_name: "prod_repo"
  base_dir: "/var/git_ops"

# Validation settings
validation:
  enable: true  # Enable validation checks for repo creation
  max_repo_size: 100MB  # Max size limit for repository
```