```yaml
# Configuration file for Git Operations

# Default environment settings
default:
  # Directory to store repositories
  repository_dir: "./repositories"
  # Logging level
  log_level: "INFO"

# Development environment settings
development:
  repository_dir: "./dev_repositories"
  log_level: "DEBUG"

# Production environment settings
production:
  repository_dir: "/var/repos"
  log_level: "ERROR"

# Validation settings for the repository
validation:
  max_repo_size_mb: 100
  allowed_file_types: 
    - "py"
    - "txt"
    - "md"

# Example for environment-specific overrides
# Uncomment and modify as needed for different environments
# dev:
#   repository_dir: "./dev_repos"
#   log_level: "DEBUG"
```