```yaml
# Configuration file for Git Operations

git_operations:
  # Default settings for Git repository operations
  default_repo_name: "my_git_repo"  # Default repository name
  log_level: "INFO"                  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

environments:
  development:
    repo_name: "dev_repo"            # Repository name for development
    log_level: "DEBUG"               # Logging level for development
  testing:
    repo_name: "test_repo"           # Repository name for testing
    log_level: "WARNING"             # Logging level for testing
  production:
    repo_name: "prod_repo"           # Repository name for production
    log_level: "ERROR"               # Logging level for production

# Validation settings
validation:
  enabled: true                      # Enable or disable validation
  rules:
    - name: "repo_name_format"       # Rule for repository name format
      pattern: "^[a-zA-Z0-9_-]+$"    # Regex pattern to validate repo names
      message: "Invalid repository name format."
```