```ini
[DEFAULT]
# Default configuration settings
log_level = INFO
timeout = 30

[development]
# Development environment settings
debug = True
database_url = sqlite:///dev.db

[testing]
# Testing environment settings
debug = False
database_url = sqlite:///test.db

[production]
# Production environment settings
debug = False
database_url = postgresql://user:pass@localhost/prod

[validation]
# Validation settings
enable_validation = True
validation_timeout = 10
```