```yaml
# Configuration file for GitOperations project

# Global settings
global:
  log_level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  max_retries: 3   # Number of retries for failed operations

# Environment-specific settings
environments:
  development:
    git_path: /usr/bin/git  # Path to the git executable
    repo_base: /tmp/dev_repos  # Base directory for repositories

  testing:
    git_path: /usr/bin/git
    repo_base: /tmp/test_repos

  production:
    git_path: /usr/local/bin/git
    repo_base: /var/repos

# Validation settings
validation:
  enabled: true  # Enable or disable validation checks
  rules:
    - check_empty_repo: true  # Enforce checks for empty repositories
    - check_git_installed: true  # Ensure Git is installed before operations
```