```yaml
# Configuration File

# Default settings for different environments
settings:
  development:
    debug: true
    database_url: "sqlite:///dev.db"
    logging_level: "DEBUG"
  testing:
    debug: false
    database_url: "sqlite:///test.db"
    logging_level: "INFO"
  production:
    debug: false
    database_url: "postgresql://user:password@localhost/prod"
    logging_level: "ERROR"

# General application settings
app:
  name: "GitOperationsApp"
  version: "1.0.0"

# Git settings
git:
  username: "your_git_username"
  email: "your_email@example.com"

# Validation
validation:
  enabled: true
  rules:
    - type: "required"
      fields: ["database_url", "git.username", "git.email"]
```