```yaml
# Configuration file for Git Operations

# Default settings
default:
  repo_name: "my_repo"  # Default repository name
  log_level: "INFO"     # Logging level (DEBUG, INFO, WARNING, ERROR)

# Development environment settings
development:
  repo_name: "dev_repo"  # Repository name for development
  log_level: "DEBUG"     # More verbose logging for development

# Testing environment settings
testing:
  repo_name: "test_repo"  # Repository name for testing
  log_level: "WARNING"    # Less verbose logging for tests

# Production environment settings
production:
  repo_name: "prod_repo"  # Repository name for production
  log_level: "ERROR"      # Minimal logging for production

# Validation configuration
validation:
  enabled: true          # Enable configuration validation
  rules:
    - type: "string"
      key: "repo_name"
      required: true
    - type: "string"
      key: "log_level"
      allowed_values: ["DEBUG", "INFO", "WARNING", "ERROR"]
```