```ini
[DEFAULT]
# Default settings for the application
repo_name = "my_repo"
log_level = "INFO"

[development]
# Development environment settings
debug = true
database_url = "sqlite:///dev.db"

[testing]
# Testing environment settings
debug = false
database_url = "sqlite:///test.db"
test_mode = true

[production]
# Production environment settings
debug = false
database_url = "postgresql://user:password@localhost/prod_db"
log_level = "ERROR"

[validation]
# Validation settings
validate_schema = true
max_repo_size = 104857600  # 100 MB
```