```yaml
# Configuration file for Git operations

# Default settings
default:
  repository_path: "./repositories"  # Default path for repositories
  git_command: "git"                   # Command to run Git
  log_level: "info"                    # Logging level (info, debug, error)

# Development environment settings
dev:
  repository_path: "./dev_repositories"  # Path for dev repositories
  log_level: "debug"                     # Logging level for development

# Testing environment settings
test:
  repository_path: "./test_repositories"  # Path for test repositories
  log_level: "error"                      # Logging level for testing

# Production environment settings
prod:
  repository_path: "./prod_repositories"  # Path for production repositories
  log_level: "info"                       # Logging level for production

# Validation rules
validation:
  repository_name_regex: "^[a-zA-Z0-9_-]+$"  # Regex to validate repository names
  max_repository_name_length: 50              # Maximum length for repository names
```