```yaml
# Configuration settings for Git operations

# Default settings
default:
  git_path: "/usr/bin/git"  # Path to the Git binary
  repository_dir: "./repos"  # Default directory for repositories
  log_level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR)

# Development environment settings
development:
  repository_dir: "./dev_repos"  # Directory for development repositories
  log_level: "DEBUG"  # More verbose logging for development

# Testing environment settings
testing:
  repository_dir: "./test_repos"  # Directory for test repositories
  log_level: "WARNING"  # Less verbose logging for tests

# Production environment settings
production:
  repository_dir: "/var/repos"  # Directory for production repositories
  log_level: "ERROR"  # Minimal logging in production

# Validation of configurations
validation:
  required_keys:
    - git_path
    - repository_dir
  valid_log_levels:
    - DEBUG
    - INFO
    - WARNING
    - ERROR
```