```yaml
# Configuration file for Git Operations

# Environment settings
environments:
  development:
    repo_path: "./dev_repos"
    log_level: "DEBUG"
    
  testing:
    repo_path: "./test_repos"
    log_level: "INFO"
    
  production:
    repo_path: "./prod_repos"
    log_level: "ERROR"

# Git settings
git:
  user_name: "Your Name"
  user_email: "your.email@example.com"
  
# Validation settings
validation:
  enabled: true
  check_interval: 60  # in seconds

# Default branch name
default_branch: "main"

# Comments:
# - Modify the repo_path based on your environment.
# - Log level can be changed to control verbosity.
# - Ensure user details are accurate for commits.
```