```yaml
# Configuration file for Git Operations

# Default settings
default:
  git_command: "git"  # Command to use for Git operations
  log_level: "INFO"    # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

# Development environment settings
development:
  repo_path: "dev_repos"  # Path to development repositories
  auto_commit: false       # Enable auto-commit on changes
  branch_name: "develop"   # Default branch for development

# Testing environment settings
testing:
  repo_path: "test_repos"  # Path to testing repositories
  auto_commit: false       # Enable auto-commit on changes
  branch_name: "test"      # Default branch for testing

# Production environment settings
production:
  repo_path: "prod_repos"  # Path to production repositories
  auto_commit: true         # Enable auto-commit on changes
  branch_name: "main"       # Default branch for production

# Validation rules
validation:
  repo_name_pattern: "^[a-zA-Z0-9_-]+$"  # Regex pattern for valid repository names
```