```ini
[DEFAULT]
# Default settings
log_level = INFO
max_retries = 3

[development]
# Development environment settings
debug = True
database_url = sqlite:///dev.db
api_endpoint = http://localhost:5000/api

[testing]
# Testing environment settings
debug = False
database_url = sqlite:///test.db
api_endpoint = http://localhost:5000/api

[production]
# Production environment settings
debug = False
database_url = postgresql://user:password@localhost/prod_db
api_endpoint = https://api.example.com

[validation]
# Validation settings
require_ssl = True
allowed_hosts = localhost, api.example.com
```