```ini
[DEFAULT]
# Default configuration settings
git_command = "git"
repo_base_path = "./repositories"

[development]
# Development environment settings
debug_mode = True
repo_name = "dev_repo"

[testing]
# Testing environment settings
debug_mode = False
repo_name = "test_repo"

[production]
# Production environment settings
debug_mode = False
repo_name = "prod_repo"

[validation]
# Configuration validation settings
validate_repo_name = true
validate_git_command = true
```