```yaml
# Configuration file for GitOperations

# Default settings for different environments
environments:
  development:
    debug: true
    repo_base_path: "./repos/dev"
  testing:
    debug: false
    repo_base_path: "./repos/test"
  production:
    debug: false
    repo_base_path: "./repos/prod"

# Logging settings
logging:
  level: INFO
  log_file: "./logs/git_operations.log"

# Repository settings
repository:
  max_repos: 100          # Maximum number of repositories allowed
  validate_repo_name: true # Validate repository names (only alphanumeric and underscores)

# Ensure proper validation of configuration
validation:
  schema:
    type: object
    properties:
      environments:
        type: object
      logging:
        type: object
      repository:
        type: object
    required: [environments, logging, repository]
```